### ISSUE TITLE
deployment/build-s3-dist.sh problem

### ISSUE THREAD

**Issue by hktdc-spwong** [aws-solutions/aws-firewall-manager-automations-for-aws-organizations#15]
**Describe the bug**

When running `deployment/build-s3-dist.sh`, it cannot find the `$template_dir/cdk-solution-helper/index`
Is it expected? Thanks.

**To Reproduce**

Run `deployment/build-s3-dist.sh` such as 
`./build-s3-dist.sh solutions solutions-reference trademarked-solution-name v1.0.0`

**Expected behavior**

Not sure if this script works.

**Please complete the following information about the solution:**

- Version:  v2.0.2

**Screenshots**
![image](https://user-images.githubusercontent.com/118430882/202393883-26416685-ec3e-40be-8010-62bc5c0fe871.png)

**Additional context**
N/A

**Comment by WillAWS** [comment]
It seems to be that an entire directory is missing (/cdk-solution-helper). For a work around, copy the directory contents from this similar project and run the same command: https://github.com/aws-solutions/aws-devops-monitoring-dashboard/tree/main/deployment/cdk-solution-helper. We'll add this task to our backlog.

**Comment by WillAWS** [comment]
This issue has been fixed by the v2.0.3 release. Closing the ticket.
